#!/bin/sh

# If a ZooKeeper container is linked with the alias `zookeeper`, use it.
# You MUST set ZOOKEEPER_IP in env otherwise.
[ -n "$ZOOKEEPER_PORT_2181_TCP_ADDR" ] && ZOOKEEPER_IP=$ZOOKEEPER_PORT_2181_TCP_ADDR
[ -n "$ZOOKEEPER_PORT_2181_TCP_PORT" ] && ZOOKEEPER_PORT=$ZOOKEEPER_PORT_2181_TCP_PORT

IP=$(grep "\s${HOSTNAME}$" /etc/hosts | head -n 1 | awk '{print $1}')

# Concatenate the IP:PORT for ZooKeeper to allow setting a full connection
# string with multiple ZooKeeper hosts
[ -z "$ZOOKEEPER_CONNECTION_STRING" ] && ZOOKEEPER_CONNECTION_STRING="${ZOOKEEPER_IP}:${ZOOKEEPER_PORT:-2181}"

cat ./config/server.properties.template | sed \
	-e "s|{{ADVERTISED_LISTENERS}}|${KAFKA_ADVERTISED_LISTENERS:-$IP:9092}|g" \
    -e "s|{{INTER_BROKER_PROTOCOL_VERSION}}|${KAFKA_INTER_BROKER_PROTOCOL_VERSION:-KAFKA_VERSION}|g" \
    -e "s|{{LOG_MESSAGE_FORMAT_VERSION}}|${KAFKA_LOG_MESSAGE_FORMAT_VERSION:-KAFKA_VERSION}|g" \
    -e "s|{{ZOOKEEPER_CONNECT}}|${KAFKA_ZOOKEEPER_CONNECT:-}|g" \
    -e "s|{{AUTO_CREATE_TOPICS_ENABLE}}|${KAFKA_AUTO_CREATE_TOPICS_ENABLE:-true}|g" \
    -e "s|{{AUTO_LEADER_REBALANCE_ENABLE}}|${KAFKA_AUTO_LEADER_REBALANCE_ENABLE:-true}|g" \
    -e "s|{{BACKGROUND_THREADS}}|${KAFKA_BACKGROUND_THREADS:-10}|g" \
    -e "s|{{BROKER_ID}}|${KAFKA_BROKER_ID:--1}|g" \
    -e "s|{{COMPRESSION_TYPE}}|${KAFKA_COMPRESSION_TYPE:-producer}|g" \
    -e "s|{{DELETE_TOPIC_ENABLE}}|${KAFKA_DELETE_TOPIC_ENABLE:-false}|g" \
    -e "s|{{LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS}}|${KAFKA_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS:-300}|g" \
    -e "s|{{LEADER_IMBALANCE_PER_BROKER_PERCENTAGE}}|${KAFKA_LEADER_IMBALANCE_PER_BROKER_PERCENTAGE:-10}|g" \
    -e "s|{{LISTENERS}}|${KAFKA_LISTENERS:-null}|g" \
    -e "s|{{LOG_DIR}}|${KAFKA_LOG_DIR:-/tmp/kafka-logs}|g" \
    -e "s|{{LOG_DIRS}}|${KAFKA_LOG_DIRS:-null}|g" \
    -e "s|{{LOG_FLUSH_INTERVAL_MESSAGES}}|${KAFKA_LOG_FLUSH_INTERVAL_MESSAGES:-9223372036854775807}|g" \
    -e "s|{{LOG_FLUSH_INTERVAL_MS}}|${KAFKA_LOG_FLUSH_INTERVAL_MS:-null}|g" \
    -e "s|{{LOG_FLUSH_OFFSET_CHECKPOINT_INTERVAL_MS}}|${KAFKA_LOG_FLUSH_OFFSET_CHECKPOINT_INTERVAL_MS:-60000}|g" \
    -e "s|{{LOG_FLUSH_SCHEDULER_INTERVAL_MS}}|${KAFKA_LOG_FLUSH_SCHEDULER_INTERVAL_MS:-9223372036854775807}|g" \
    -e "s|{{LOG_RETENTION_BYTES}}|${KAFKA_LOG_RETENTION_BYTES:--1}|g" \
    -e "s|{{LOG_RETENTION_HOURS}}|${KAFKA_LOG_RETENTION_HOURS:-168}|g" \
    -e "s|{{LOG_RETENTION_MINUTES}}|${KAFKA_LOG_RETENTION_MINUTES:-null}|g" \
    -e "s|{{LOG_RETENTION_MS}}|${KAFKA_LOG_RETENTION_MS:-null}|g" \
    -e "s|{{LOG_ROLL_HOURS}}|${KAFKA_LOG_ROLL_HOURS:-168}|g" \
    -e "s|{{LOG_ROLL_JITTER_HOURS}}|${KAFKA_LOG_ROLL_JITTER_HOURS:-0}|g" \
    -e "s|{{LOG_ROLL_JITTER_MS}}|${KAFKA_LOG_ROLL_JITTER_MS:-null}|g" \
    -e "s|{{LOG_ROLL_MS}}|${KAFKA_LOG_ROLL_MS:-null}|g" \
    -e "s|{{LOG_SEGMENT_BYTES}}|${KAFKA_LOG_SEGMENT_BYTES:-1073741824}|g" \
    -e "s|{{LOG_SEGMENT_DELETE_DELAY_MS}}|${KAFKA_LOG_SEGMENT_DELETE_DELAY_MS:-60000}|g" \
    -e "s|{{MESSAGE_MAX_BYTES}}|${KAFKA_MESSAGE_MAX_BYTES:-1000012}|g" \
    -e "s|{{MIN_INSYNC_REPLICAS}}|${KAFKA_MIN_INSYNC_REPLICAS:-1}|g" \
    -e "s|{{NUM_IO_THREADS}}|${KAFKA_NUM_IO_THREADS:-8}|g" \
    -e "s|{{NUM_NETWORK_THREADS}}|${KAFKA_NUM_NETWORK_THREADS:-3}|g" \
    -e "s|{{NUM_RECOVERY_THREADS_PER_DATA_DIR}}|${KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR:-1}|g" \
    -e "s|{{NUM_REPLICA_FETCHERS}}|${KAFKA_NUM_REPLICA_FETCHERS:-1}|g" \
    -e "s|{{OFFSET_METADATA_MAX_BYTES}}|${KAFKA_OFFSET_METADATA_MAX_BYTES:-4096}|g" \
    -e "s|{{OFFSETS_COMMIT_REQUIRED_ACKS}}|${KAFKA_OFFSETS_COMMIT_REQUIRED_ACKS:--1}|g" \
    -e "s|{{OFFSETS_COMMIT_TIMEOUT_MS}}|${KAFKA_OFFSETS_COMMIT_TIMEOUT_MS:-5000}|g" \
    -e "s|{{OFFSETS_LOAD_BUFFER_SIZE}}|${KAFKA_OFFSETS_LOAD_BUFFER_SIZE:-5242880}|g" \
    -e "s|{{OFFSETS_RETENTION_CHECK_INTERVAL_MS}}|${KAFKA_OFFSETS_RETENTION_CHECK_INTERVAL_MS:-600000}|g" \
    -e "s|{{OFFSETS_RETENTION_MINUTES}}|${KAFKA_OFFSETS_RETENTION_MINUTES:-1440}|g" \
    -e "s|{{OFFSETS_TOPIC_COMPRESSION_CODEC}}|${KAFKA_OFFSETS_TOPIC_COMPRESSION_CODEC:-0}|g" \
    -e "s|{{OFFSETS_TOPIC_NUM_PARTITIONS}}|${KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS:-50}|g" \
    -e "s|{{OFFSETS_TOPIC_REPLICATION_FACTOR}}|${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:-3}|g" \
    -e "s|{{OFFSETS_TOPIC_SEGMENT_BYTES}}|${KAFKA_OFFSETS_TOPIC_SEGMENT_BYTES:-104857600}|g" \
    -e "s|{{QUEUED_MAX_REQUESTS}}|${KAFKA_QUEUED_MAX_REQUESTS:-500}|g" \
    -e "s|{{REPLICA_FETCH_MIN_BYTES}}|${KAFKA_REPLICA_FETCH_MIN_BYTES:-1}|g" \
    -e "s|{{REPLICA_FETCH_WAIT_MAX_MS}}|${KAFKA_REPLICA_FETCH_WAIT_MAX_MS:-500}|g" \
    -e "s|{{REPLICA_HIGH_WATERMARK_CHECKPOINT_INTERVAL_MS}}|${KAFKA_REPLICA_HIGH_WATERMARK_CHECKPOINT_INTERVAL_MS:-5000}|g" \
    -e "s|{{REPLICA_LAG_TIME_MAX_MS}}|${KAFKA_REPLICA_LAG_TIME_MAX_MS:-10000}|g" \
    -e "s|{{REPLICA_SOCKET_RECEIVE_BUFFER_BYTES}}|${KAFKA_REPLICA_SOCKET_RECEIVE_BUFFER_BYTES:-65536}|g" \
    -e "s|{{REPLICA_SOCKET_TIMEOUT_MS}}|${KAFKA_REPLICA_SOCKET_TIMEOUT_MS:-30000}|g" \
    -e "s|{{REQUEST_TIMEOUT_MS}}|${KAFKA_REQUEST_TIMEOUT_MS:-30000}|g" \
    -e "s|{{SOCKET_RECEIVE_BUFFER_BYTES}}|${KAFKA_SOCKET_RECEIVE_BUFFER_BYTES:-102400}|g" \
    -e "s|{{SOCKET_REQUEST_MAX_BYTES}}|${KAFKA_SOCKET_REQUEST_MAX_BYTES:-104857600}|g" \
    -e "s|{{SOCKET_SEND_BUFFER_BYTES}}|${KAFKA_SOCKET_SEND_BUFFER_BYTES:-102400}|g" \
    -e "s|{{UNCLEAN_LEADER_ELECTION_ENABLE}}|${KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE:-true}|g" \
    -e "s|{{ZOOKEEPER_CONNECTION_TIMEOUT_MS}}|${KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS:-null}|g" \
    -e "s|{{ZOOKEEPER_SESSION_TIMEOUT_MS}}|${KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS:-6000}|g" \
    -e "s|{{ZOOKEEPER_SET_ACL}}|${KAFKA_ZOOKEEPER_SET_ACL:-false}|g" \
    -e "s|{{BROKER_ID_GENERATION_ENABLE}}|${KAFKA_BROKER_ID_GENERATION_ENABLE:-true}|g" \
    -e "s|{{BROKER_RACK}}|${KAFKA_BROKER_RACK:-null}|g" \
    -e "s|{{CONNECTIONS_MAX_IDLE_MS}}|${KAFKA_CONNECTIONS_MAX_IDLE_MS:-600000}|g" \
    -e "s|{{CONTROLLED_SHUTDOWN_ENABLE}}|${KAFKA_CONTROLLED_SHUTDOWN_ENABLE:-true}|g" \
    -e "s|{{CONTROLLED_SHUTDOWN_MAX_RETRIES}}|${KAFKA_CONTROLLED_SHUTDOWN_MAX_RETRIES:-3}|g" \
    -e "s|{{CONTROLLED_SHUTDOWN_RETRY_BACKOFF_MS}}|${KAFKA_CONTROLLED_SHUTDOWN_RETRY_BACKOFF_MS:-5000}|g" \
    -e "s|{{CONTROLLER_SOCKET_TIMEOUT_MS}}|${KAFKA_CONTROLLER_SOCKET_TIMEOUT_MS:-30000}|g" \
    -e "s|{{DEFAULT_REPLICATION_FACTOR}}|${KAFKA_DEFAULT_REPLICATION_FACTOR:-1000}|g" \
    -e "s|{{FETCH_PURGATORY_PURGE_INTERVAL_REQUESTS}}|${KAFKA_FETCH_PURGATORY_PURGE_INTERVAL_REQUESTS:-1000}|g" \
    -e "s|{{GROUP_MAX_SESSION_TIMEOUT_MS}}|${KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS:-300000}|g" \
    -e "s|{{GROUP_MIN_SESSION_TIMEOUT_MS}}|${KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS:-6000}|g" \
    -e "s|{{INTER_BROKER_LISTENER_NAME}}|${KAFKA_INTER_BROKER_LISTENER_NAME:-null}|g" \
    -e "s|{{LOG_CLEANER_BACKOFF_MS}}|${KAFKA_LOG_CLEANER_BACKOFF_MS:-15000}|g" \
    -e "s|{{LOG_CLEANER_DEDUPE_BUFFER_SIZE}}|${KAFKA_LOG_CLEANER_DEDUPE_BUFFER_SIZE:-134217728}|g" \
    -e "s|{{LOG_CLEANER_DELETE_RETENTION_MS}}|${KAFKA_LOG_CLEANER_DELETE_RETENTION_MS:-86400000}|g" \
    -e "s|{{LOG_CLEANER_ENABLE}}|${KAFKA_LOG_CLEANER_ENABLE:-true}|g" \
    -e "s|{{LOG_CLEANER_IO_BUFFER_LOAD_FACTOR}}|${KAFKA_LOG_CLEANER_IO_BUFFER_LOAD_FACTOR:-0.9}|g" \
    -e "s|{{LOG_CLEANER_IO_BUFFER_SIZE}}|${KAFKA_LOG_CLEANER_IO_BUFFER_SIZE:-5247288}|g" \
    -e "s|{{LOG_CLEANER_IO_MAX_BYTES_PER_SECOND}}|${KAFKA_LOG_CLEANER_IO_MAX_BYTES_PER_SECOND:-1.7976931348623157E308}|g" \
    -e "s|{{LOG_CLEANER_MIN_CLEANABLE_RATIO}}|${KAFKA_LOG_CLEANER_MIN_CLEANABLE_RATIO:-0.5}|g" \
    -e "s|{{LOG_CLEANER_MIN_COMPACTION_LAG_MS}}|${KAFKA_LOG_CLEANER_MIN_COMPACTION_LAG_MS:-0}|g" \
    -e "s|{{LOG_CLEANER_THREADS}}|${KAFKA_LOG_CLEANER_THREADS:-1}|g" \
    -e "s|{{LOG_CLEANUP_POLICY}}|${KAFKA_LOG_CLEANUP_POLICY:-delete}|g" \
    -e "s|{{LOG_INDEX_INTERVAL_BYTES}}|${KAFKA_LOG_INDEX_INTERVAL_BYTES:-4096}|g" \
    -e "s|{{LOG_INDEX_SIZE_MAX_BYTES}}|${KAFKA_LOG_INDEX_SIZE_MAX_BYTES:-10485760}|g" \
    -e "s|{{LOG_MESSAGE_TIMESTAMP_DIFFERENCE_MAX_MS}}|${KAFKA_LOG_MESSAGE_TIMESTAMP_DIFFERENCE_MAX_MS:-9223372036854775807}|g" \
    -e "s|{{LOG_MESSAGE_TIMESTAMP_TYPE}}|${KAFKA_LOG_MESSAGE_TIMESTAMP_TYPE:-CreateTIme}|g" \
    -e "s|{{LOG_PREALLOCATE}}|${KAFKA_LOG_PREALLOCATE:-false}|g" \
    -e "s|{{LOG_RETENTION_CHECK_INTERVAL_MS}}|${KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS:-300000}|g" \
    -e "s|{{MAX_CONNECTIONS_PER_IP}}|${KAFKA_MAX_CONNECTIONS_PER_IP:-2147483647}|g" \
    -e "s|{{MAX_CONNECTIONS_PER_IP_OVERRIDES}}|${KAFKA_MAX_CONNECTIONS_PER_IP_OVERRIDES:-\"\"}|g" \
    -e "s|{{NUM_PARTITIONS}}|${KAFKA_NUM_PARTITIONS:-1}|g" \
    -e "s|{{PRINCIPAL_BUILDER_CLASS}}|${KAFKA_PRINCIPAL_BUILDER_CLASS:-org.apache.kafka.common.security.auth.DefaultPrincipalBuilder}|g" \
    -e "s|{{PRODUCER_PURGATORY_PURGE_INTERVAL_REQUESTS}}|${KAFKA_PRODUCER_PURGATORY_PURGE_INTERVAL_REQUESTS:-1000}|g" \
    -e "s|{{REPLICA_FETCH_BACKOFF_MS}}|${KAFKA_REPLICA_FETCH_BACKOFF_MS:-1000}|g" \
    -e "s|{{REPLICA_FETCH_MAX_BYTES}}|${KAFKA_REPLICA_FETCH_MAX_BYTES:-1048576}|g" \
    -e "s|{{REPLICA_FETCH_RESPONSE_MAX_BYTES}}|${KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES:-10485760}|g" \
    -e "s|{{RESERVED_BROKER_MAX_ID}}|${KAFKA_RESERVED_BROKER_MAX_ID:-1000}|g" \
    -e "s|{{SASL_ENABLED_MECHANISMS}}|${KAFKA_SASL_ENABLED_MECHANISMS:-GSSAPI}|g" \
    -e "s|{{SASL_KERBEROS_KINIT_CMD}}|${KAFKA_SASL_KERBEROS_KINIT_CMD:-/usr/bin/kinit	medium}|g" \
    -e "s|{{SASL_KERBEROS_MIN_TIME_BEFORE_RELOGIN}}|${KAFKA_SASL_KERBEROS_MIN_TIME_BEFORE_RELOGIN:-60000}|g" \
    -e "s|{{SASL_KERBEROS_PRINCIPAL_TO_LOCAL_RULES}}|${KAFKA_SASL_KERBEROS_PRINCIPAL_TO_LOCAL_RULES:-DEFAULT}|g" \
    -e "s|{{SASL_KERBEROS_SERVICE_NAME}}|${KAFKA_SASL_KERBEROS_SERVICE_NAME:-null}|g" \
    -e "s|{{SASL_KERBEROS_TICKET_RENEW_JITTER}}|${KAFKA_SASL_KERBEROS_TICKET_RENEW_JITTER:-0.05}|g" \
    -e "s|{{SASL_KERBEROS_TICKET_RENEW_WINDOW_FACTOR}}|${KAFKA_SASL_KERBEROS_TICKET_RENEW_WINDOW_FACTOR:-0.8}|g" \
    -e "s|{{SASL_MECHANISM_INTER_BROKER_PROTOCOL}}|${KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL:-GSSAPI}|g" \
    -e "s|{{SECURITY_INTER_BROKER_PROTOCOL}}|${KAFKA_SECURITY_INTER_BROKER_PROTOCOL:-PLAINTEXT}|g" \
    -e "s|{{SSL_CIPHER_SUITES}}|${KAFKA_SSL_CIPHER_SUITES:-null}|g" \
    -e "s|{{SSL_CLIENT_AUTH}}|${KAFKA_SSL_CLIENT_AUTH:-none}|g" \
    -e "s|{{SSL_ENABLED_PROTOCOLS}}|${KAFKA_SSL_ENABLED_PROTOCOLS:-TLSv1.2,TLSv1.1,TLSv1}|g" \
    -e "s|{{SSL_KEY_PASSWORD}}|${KAFKA_SSL_KEY_PASSWORD:-null}|g" \
    -e "s|{{SSL_KEYMANAGER_ALGORITHM}}|${KAFKA_SSL_KEYMANAGER_ALGORITHM:-SunX509}|g" \
    -e "s|{{SSL_KEYSTORE_LOCATION}}|${KAFKA_SSL_KEYSTORE_LOCATION:-null}|g" \
    -e "s|{{SSL_KEYSTORE_PASSWORD}}|${KAFKA_SSL_KEYSTORE_PASSWORD:-null}|g" \
    -e "s|{{SSL_KEYSTORE_TYPE}}|${KAFKA_SSL_KEYSTORE_TYPE:-JKS}|g" \
    -e "s|{{SSL_PROTOCOL}}|${KAFKA_SSL_PROTOCOL:-TLS}|g" \
    -e "s|{{SSL_PROVIDER}}|${KAFKA_SSL_PROVIDER:-null}|g" \
    -e "s|{{SSL_TRUSTMANAGER_ALGORITHM}}|${KAFKA_SSL_TRUSTMANAGER_ALGORITHM:-PKIX}|g" \
    -e "s|{{SSL_TRUSTSTORE_LOCATION}}|${KAFKA_SSL_TRUSTSTORE_LOCATION:-null}|g" \
    -e "s|{{SSL_TRUSTSTORE_PASSWORD}}|${KAFKA_SSL_TRUSTSTORE_PASSWORD:-}|g" \
    -e "s|{{SSL_TRUSTSTORE_TYPE}}|${KAFKA_SSL_TRUSTSTORE_TYPE:-JKS}|g" \
    -e "s|{{AUTHORIZER_CLASS_NAME}}|${KAFKA_AUTHORIZER_CLASS_NAME:-\"\"}|g" \
    -e "s|{{CREATE_TOPIC_POLICY_CLASS_NAME}}|${KAFKA_CREATE_TOPIC_POLICY_CLASS_NAME:-null}|g" \
    -e "s|{{LISTENER_SECURITY_PROTOCOL_MAP}}|${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:-SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,TRACE:TRACE,SASL_SSL:SASL_SSL,PLAINTEXT:PLAINTEXT}|g" \
    -e "s|{{METRIC_REPORTERS}}|${KAFKA_METRIC_REPORTERS:-\"\"}|g" \
    -e "s|{{METRICS_NUM_SAMPLES}}|${KAFKA_METRICS_NUM_SAMPLES:-2}|g" \
    -e "s|{{METRICS_RECORDING_LEVEL}}|${KAFKA_METRICS_RECORDING_LEVEL:-INFO}|g" \
    -e "s|{{METRICS_SAMPLE_WINDOW_MS}}|${KAFKA_METRICS_SAMPLE_WINDOW_MS:-30000}|g" \
    -e "s|{{QUOTA_WINDOW_NUM}}|${KAFKA_QUOTA_WINDOW_NUM:-11}|g" \
    -e "s|{{QUOTA_WINDOW_SIZE_SECONDS}}|${KAFKA_QUOTA_WINDOW_SIZE_SECONDS:-1}|g" \
    -e "s|{{REPLICATION_QUOTA_WINDOW_NUM}}|${KAFKA_REPLICATION_QUOTA_WINDOW_NUM:-11}|g" \
    -e "s|{{REPLICATION_QUOTA_WINDOW_SIZE_SECONDS}}|${KAFKA_REPLICATION_QUOTA_WINDOW_SIZE_SECONDS:-1}|g" \
    -e "s|{{SSL_ENDPOINT_IDENTIFICATION_ALGORITHM}}|${KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM:-null}|g" \
    -e "s|{{SSL_SECURE_RANDOM_IMPLEMENTATION}}|${KAFKA_SSL_SECURE_RANDOM_IMPLEMENTATION:-null}|g" \
    -e "s|{{ZOOKEEPER_SYNC_TIME_MS}}|${KAFKA_ZOOKEEPER_SYNC_TIME_MS:-2000}|g" \
> /kafka/config/server.properties

# Kafka's built-in start scripts set the first three system properties here, but
# we add two more to make remote JMX easier/possible to access in a Docker
# environment:
#
#   1. RMI port - pinning this makes the JVM use a stable one instead of
#      selecting random high ports each time it starts up.
#   2. RMI hostname - normally set automatically by heuristics that may have
#      hard-to-predict results across environments.
#
# These allow saner configuration for firewalls, EC2 security groups, Docker
# hosts running in a VM with Docker Machine, etc. See:
#
# https://issues.apache.org/jira/browse/CASSANDRA-7087
if [ -z $KAFKA_JMX_OPTS ]; then
    KAFKA_JMX_OPTS="-Dcom.sun.management.jmxremote=true"
    KAFKA_JMX_OPTS="$KAFKA_JMX_OPTS -Dcom.sun.management.jmxremote.authenticate=false"
    KAFKA_JMX_OPTS="$KAFKA_JMX_OPTS -Dcom.sun.management.jmxremote.ssl=false"
    KAFKA_JMX_OPTS="$KAFKA_JMX_OPTS -Dcom.sun.management.jmxremote.rmi.port=$JMX_PORT"
    KAFKA_JMX_OPTS="$KAFKA_JMX_OPTS -Djava.rmi.server.hostname=${JAVA_RMI_SERVER_HOSTNAME:-$KAFKA_ADVERTISED_HOST_NAME} "
    export KAFKA_JMX_OPTS
fi

if [ -z $KAFKA_HEAP_OPTS ]; then
	KAFKA_HEAP_OPTS = ""

	# 初始堆大小 物理内存的1/64(<1GB)
	if [ -n $JAVA_HEAP_XMS]; then
		KAFKA_HEAP_OPTS="$KAFKA_HEAP_OPTS -Xms${JAVA_HEAP_XMS}"
	fi

	# 最大堆大小 物理内存的1/4(<1GB)
	if [ -n $JAVA_HEAP_XMX]; then
		KAFKA_HEAP_OPTS="$KAFKA_HEAP_OPTS -Xmx${JAVA_HEAP_XMX}"
	fi
	# 设置持久代(perm gen)初始值
	if [ -n $JAVA_HEAP_PERM_SIZE]; then
		KAFKA_HEAP_OPTS="$KAFKA_HEAP_OPTS -XX:PermSize=${JAVA_HEAP_PERM_SIZE}"
	fi
	# 设置持久代最大值
	if [ -n $JAVA_HEAP_MAX_PERM_SIZE]; then
		KAFKA_HEAP_OPTS="$KAFKA_HEAP_OPTS -XX:MaxPermSize=${JAVA_HEAP_MAX_PERM_SIZE}"
	# 每次年轻代垃圾回收的最长时间(最大暂停时间)
	if [ -n $JAVA_HEAP_MAX_GC_PAUSE_MILLIS]; then
		KAFKA_HEAP_OPTS="$KAFKA_HEAP_OPTS -XX:MaxGCPauseMillis=${JAVA_HEAP_MAX_GC_PAUSE_MILLIS}"
	fi

	if [ -n $JAVA_HEAP_INITIATING_HEAP_OCCUPANCY_PERCENT]; then
		KAFKA_HEAP_OPTS="$KAFKA_HEAP_OPTS -XX:InitiatingHeapOccupancyPercent=${JAVA_HEAP_INITIATING_HEAP_OCCUPANCY_PERCENT}"
	fi

	KAFKA_HEAP_OPTS="$KAFKA_HEAP_OPTS -XX:+UseG1GC"
	export KAFKA_HEAP_OPTS
fi

echo "Starting kafka"
exec kafka-server-start.sh ./config/server.properties